### PR TITLE
Unification pass on data files

### PR DESCRIPTION
**Pull request by TristanHehnen**
Hi,

I've unified a couple of file names and headers in the data files. I've also changed the DBI/Lund data file names from "DBI_Lund" to "DBI-Lund" to easier process file names (split around the "_").

Best,
Tristan

### CODE REVIEW

**Comment by TristanHehnen** [comment]
And also added numbers for the repetitions to file names of tests that have only a single repetition. Again, for easier processing.

**Review by leventon — CHANGES_REQUESTED** [review]
This all looks good, straightforward but useful changes for automatic processing. Thank you, Tristan.

Since you updated some instances of capitalization on units (uppercase/lowercase K for temperature) can I ask that you do so consistently for all files before we accept the PR?

**Comment by TristanHehnen** [comment]
Sure, I somehow overlooked them...

**Comment by TristanHehnen** [comment]
I've adjusted the units in the remaining files.

**Comment by TristanHehnen** [comment]
Alright, I'll check them.

**Comment by TristanHehnen** [comment]
Okay, there is a couple of datasets that are providing more than just the back side temperature of the sample. I've decided to not have the respective column headers as `Temperature number`, but try to give a more meaningful description based on the `README.md`. The goal is to make it easier for people to realise that they are at different locations, even when not reading the `README.md` carefully enough (like I did). 

On a different note: LCPP merged their temperature, mass  and HRR data from the cone calorimeter into a single file. Since the temperature and HRR are recorded with different frequencies, there are a bunch of empty cells. We could  them with `NaN`.

For UClan it states in the `README.md` that the HRR was changed from kW to kW/m², based on the exposed sample surface when using a frame. However, the section concerning the usage of a retainer frame is marked as missing information. This point needs a stronger argument as to why this approach was chosen, considering that the usage of a retainer frame among the institutes is mixed. 

Also added a `README.md` skeleton for ULSTER.

For UMD seems something off with the CAPA file naming. There is two files per test, one is labelled `_Mass`, the other `_Temp`, yet both contain mass and temperature information. Could it be that these are the repetitions instead?

**Comment by TristanHehnen** [comment]
Also unified the directory label for DBI/Lund, to match the file labels.

**Comment by TristanHehnen** [comment]
I would like to add a new tag to the file labels, to be used instead of the repetition number: `_processed`. It should be used for files that are not containing basic data series. This would help with identifying data sets, when looping over all files, without the need to implement exceptions.
If I saw it correctly, for now this would only apply to the UMD data sets, because they averaged the contributed data. This step would be future proving the repository. 

In the future, institutes should then be encouraged to provide the base data series and data processed to their liking in different files. This also allows to check the inputs as well and process them differently if desired.

As an example:
`UMD_DSC_N2_10K_1.csv`
would become:
`UMD_DSC_N2_10K_processed.csv`

**Comment by leventon** [comment]
I am concerned that if we offer a "processed" option, we will lose the
standard formatting that we worked so hard to organize. If we offer that
option, what would stop every group from trying to do that uniquely?
Further, if we generally allow groups to process their data differently we
lose uniformity and, perhaps, ease in comparing datasets in the exact same
way.. safer, I think, would be to continue with writing scripts that
uniformly process all data in the same way.

**Comment by TristanHehnen** [comment]
Alright, I will not add it.

Personally, I would also prefer if people would submit their base data series.

**Comment by leventon** [comment]
Reviewing some of your notes - LCPP cone data has time, mass, HRR, and Temp data in the same column order as all other labs. I do not see the need to edit that file.

UMD CAPA data keeps the same time, Mass, Temp format as all other gasification-type tests as well. the _mass or _Temp files are designed to only hold one of those data types + an extra column with uncertainties. it was a needed workaround given how they averaged multiple tests together + reported uncertainties. changing this format would likely break the scripts processing results.

thanks for the Ulster README skeleton. their dataset + description is limited based on discussed I had with their contributing author. Perhaps we'll reconnect in the coming weeks when sharing new info and be able to add to that README.

Given new updates to adjust the repo structure for new data + property sets, your files now have a conflict (simply the folders they live in). Would you be able to merge changes as needed and resubmit this PR?

**Comment by TristanHehnen** [comment]
For files that have multiple temperature locations, the respective column headers are numbered. LCPP provides a single location. I've added the "1" for this location to allow easier processing. This might not be seen by people using the column index to access the data, but is important for people using the headers. For those using the headers, it is producing errors that need to be captured and is unnecessary. 

I assume this is also the issue that you point out with respect to the UMD files. Having these columns filled with zeros is necessary if one is looking for the column index instead of the header. Using the headers has clear benefits:
1. The user types the word of the information they are interested in. This provides a built-in error check and massively simplifies debugging.
2. When using the header instead of the index, the user does not need to care in which column the data is, which, again, leads to less errors.
I will not argue this point further for the UMD files, they are already exceptions.

**Comment by TristanHehnen** [comment]
And again...

**Comment by rmcdermo** [comment]
@leventon Please do not leave PRs hanging around this long.  Either merge them the day they come in, or close and ask the user to submit a new one later.

**Pull request closed without merging**
