### PR TITLE
Aalto_Models

### PR DESCRIPTION
**Pull request by FaridAlinejad**
We introduced two models in our study: Model 1 utilized the standard version of FDS, while Model 2 incorporated a customized version of FDS, available at https://github.com/FaridAlinejad/fds/tree/aaltofds.
The key distinction between these models resides in their approach to handling the in-depth transfer of thermal radiation.

### CODE REVIEW

**Comment by leventon** [comment]
I am confused by the naming convention of what is [Aalto1 and Aalto2] vs [Aalto I and Aalto II ] and which material property set was developed for MaCFP-2 or MaCFP-3. 

Can you please update this throughout? Perhaps labeling/referring to .json files/material property sets as only Aalto-I or Aalto-II (and in their respective READMEs IDing which MaCFP they were developed for)?

**Comment by FaridAlinejad** [comment]
We introduced two models in our study: Model_I utilized the standard version of FDS, while Model_II incorporated a customized version of FDS, available at https://github.com/FaridAlinejad/fds/tree/aaltofds.
The key distinction between these models resides in their approach to handling the in-depth transfer of thermal radiation. Both material property sets were developed for MaCFP-2.

**Comment by leventon** [comment]
Thanks, Farid. File naming now makes sense to me. 

I am still confused by the new material property set / pyrolysis model that you have defined as Aalto_II. How was that developed for MaCFP-2? It appears that is a new property set that you'd only uploaded now for MaCFP-3. 

While the file naming is now consistent, in the README files for Aalto I and Aalto II, they both identify their pyrolysis models identically (although, presumably that's the key difference from I vs. II):

"Material property set: developed by Aalto University; calibration data: University of Lille (TGA for chemical kinetics estimation), Aalto University, DBI and University of Lund (gasification for material properties estimation); calibration method used: Gpyro (chemical kinetics), PROPTI (material properties).
Comments: The accompanying numerical results are obtained using the pyrolysis model developed at Aalto University during MaCFP Phase II."

While the file naming may be consistent here, would you please also update the text description in the README files to identify (maybe even point to: /../PMMA/Material_Properties/MaCFP_PMMA_Aalto_I.json) the appropriate material property set / .json file?

**Comment by leventon** [comment]
I'm going to merge this in so that is can be considered in as we prepare our analysis for the June 20 presentation but I still am confused how you say that you're using the same properties for Aalto_II//the same properties for MaCFP-3. 

When I compare the two .json files for the Aalto_I and Aalto_II models, they have different calibration techniques and values [reaction numbers + kinetics, heat capacities, conductivity, etc. all are different when I compare https://github.com/MaCFP/matl-db/blob/master/PMMA/Material_Properties/MaCFP_PMMA_Aalto.json vs. the Aalto_II model you provide here). Thus, I don't think the comment you made, "Model 1 utilized the standard version of FDS, while Model 2 incorporated a customized version of FDS" and the later comment, "For MaCFP-3, we used the same material properties." are fully consistent/completely capture the full differences/similarities of either approach.

Perhaps I am just misunderstanding things as these comments are made piecemeal.

**Pull request merged**
