### PR TITLE
PMMA: fix line endings

### PR DESCRIPTION
**Pull request by rmcdermo**
@leventon @mcb1  We need to pay attention to line endings.  There are notes on how to handle this [here](https://github.com/firemodels/fds/wiki/Git-Notes-Line-Endings).  Whoever is merging, please double check this.  As users use our repos as submodules, we need to keep this clean.  Thanks

### CODE REVIEW

**Comment by rmcdermo** [comment]
Yes, but it does not always work, in my experience.

**Comment by TristanHehnen** [comment]
For now, I'm a bit unsure how this is supposed to work exactly. I've tried to implement the `.gitattributes` as presented in the four-step guide mentioned above. To me, there seems to be some information missing. 

If someone of you knows what might be missing there, here is a proposal how the `.gitattributes` could be structured:

```
# Handle line endings automatically for files upon commit.
# See the link for more details:
# https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
# -----------------------------------------------------------------------------

# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto

# Explicitly declare text files you want to always be normalized and converted
# to native line endings on checkout.
# *.c text

# Declare files that will always have LF line endings on checkout.
.gitattributes text eol=lf
.gitignore text eol=lf
LICENSE text eol=lf
*.txt text eol=lf
*.tex text eol=lf
*.bib text eol=lf
*.csv text eol=lf
*.py text eol=lf
*.md text eol=lf
*.m text eol=lf
*.json text eol=lf

# Declare files that will always have CRLF line endings on checkout.
# *.sln text eol=crlf

# Denote all files that are truly binary and should not be modified.
*.png binary
*.jpg binary

```

**Comment by TristanHehnen** [comment]
@rmcdermo ah, okay. I did not know this.

**Comment by TristanHehnen** [comment]
I had the issue that `git add`, `git commit` and `git push` seemed not to change the line endings. I then deleted my local repo and cloned it again, then the endings seemed to be correct.

**Comment by rmcdermo** [comment]
We have a .gitattributes in the fds repo [here](https://github.com/firemodels/fds/blob/master/.gitattributes).

Things can still get messed up.  So, I often have to fix things manually.

**Comment by TristanHehnen** [comment]
When playing around with it earlier I had the impression that the `* text=auto` was messing things up, thus I declared all files manually to be `LF`. 
Maybe this reduces the errors?

**Comment by rmcdermo** [comment]
We've tried about every combination possible.  If I were to change things now, it would mess someone up somewhere.

**Comment by TristanHehnen** [comment]
Okay, I guess you are talking about FDS now. 
Do we want to try the proposed `.gitattributes` from above here in the MaCFP: matl_db?

**Comment by TristanHehnen** [comment]
In the [`.gitattribute` in FDS](https://github.com/firemodels/fds/blob/master/.gitattributes) there are two definitions of how to deal with the `*.csv`, line 8 and line 11. 
If I understand this correctly, in the first it tells git to use the OS settings for all  CSV. In line 11 it tells git to change the endings of a specific subset to be `LF` explicitly. 
Maybe this is what is leading to errors?

**Comment by rmcdermo** [comment]
Looks like we added line 11 to deal somehow differently with the dataplot parameters.  Like I said, I dare not change anything at this point.

**Pull request merged**
