### PR TITLE
Added indication of MCC data shift for pyrolysis parameter shift.

### PR DESCRIPTION
**Pull request by TristanHehnen**

### CODE REVIEW

**Comment by TristanHehnen** [comment]
As a proposal to the discussion here:
https://groups.google.com/g/macfp-discussions/c/S61GPR4ObjY

**Comment by TristanHehnen** [comment]
Also I made an error in the commit message, should have been:
"Added indication of MCC data shift for pyrolysis parameter set."

Well, it is what it is....

**Comment by mcb1** [comment]
I think this is good information to add. I'd make it more specific, though. Maybe call this "Temperature Shift" rather than just "Shift". And we'll need to make a note of the convention. I'd suggest using dT = T_sample - T_thermocouple < 0 rather than dT = T_thermocouple - T_ sample > 0.

**Comment by leventon** [comment]
I think this shift as you describe it would likely only be used if a
calibration approach simultaneously analyzes TGA and MCC measurements (and
only if simultaneously calibrating the two for kinetic property
determination or when looking at reaction step specific heats of
combustion). I agree with Morgan that a more specific terminology should be
used if we decide to go this route but I wonder if this is a parameter that
should be requested in all JSON files (submitted by all modelers using all
different calibration approaches) or if this is more suitable as a comment
in the notes / description of this approach. As we have discussed
previously, I wouldn't necessarily try shifting the measurements, as noted
here (though you use 0k), unless both sets of experimental data from either
instrument or recorded under nominally the same heating conditions.

**Comment by TristanHehnen** [comment]
Here is a more specific way to label the parameter.

When running simulations with the submitted parameter sets, the shift is noticeable if applied. For my strategy the experiment and simulation plots overlap, since they were used as target directly. Others reflect the shift, if it was applied during the estimation. 

I think I'm fine with having information on the performed adjustments tracked in a readme file, similar to the experiment data. Important is that it is clearly tracked.
We should use the same file structure for the parameter sets as is used for the experiment data: directories with the institute labels, readme and *.json files for the submitted data.

**Comment by TristanHehnen** [comment]
I also see issues with the fact that many institutes use very different strategies to get to the parameter sets and use them. This makes me question how easy they actually are to compare. 
This gets much worse if nobody says how they actually did get to the parameter sets.

**Comment by TristanHehnen** [comment]
Hi, how is the situation here, could this PR please be merged?

**Comment by leventon** [comment]
I am concerned that this parameter would *only* be used/defined in analyses when both TGA and MCC data are analyzed simultaneously (or if MCC data is used to calibrate kinetic parameters) and temperature-resolved measurements are required for this coupled analysis (e.g., not looking at full integral quantities or comparing between relative peaks). Not every model parameterization follows this specific approach; more specifically, I believe a majority of those submitted (so far) here do not. 

Tristan, as you note, there are lots of different strategies to compare / develop these properties, and so I'm worried about defining a unique parameter/descriptor for each of these different approaches. We risk having multiple parameters/descriptors that everyone would then be asked to define, whether or not they're relevant to a given parameterization approach. With very large datasets (N parameter sets and approaches) this might be valuable if all such descriptors could be uniformly defined (and programmatically analyzed for trends) but, I think, the clearer, more complete result requires a short written description; this is currently provided/requested in the README descriptions of how these models were developed (i.e., the model questionnaire).

Further, simply defining a 'shift' Temperature, dT, is not unambiguous. dT here is not really known: it is not 'truly' sample vs. thermocouple temperature - it's estimated as apparent sample temperature given differences in measured thermocouple temperature at which different events/signals are recorded in two different apparatus (in your analysis, I believe, from tests conducted at different heating rates, which further complicates the comparison).

**Comment by mcb1** [comment]
I completely agree with Isaac. But this particular issue points to the more general problem of characterizing and comparing the different methods for finding parameters. I think Isaac is correct that the finer details of the calibration procedure should be described in the README file, but we have allowed for some minimal descriptors such as "Model", "Method", and "Scope". The value of having this minimal set of information in the JSON files is that it could potentially support comparisons of different methods---for example, if different optimization algorithms are used, which type of algorithm produces "better" parameters. So there's a sweet spot of providing a small set of well-defined useful parameters in the JSON files without letting the files blow up with information that could never be used for comparisons. Finding that sweet spot is a work in progress so I'd like to keep this discussion open elsewhere even as we close this particular issue.

**Comment by TristanHehnen** [comment]
Well, fair enough.

For now, there are no  README files for the parameter sets. While looking through the files I submitted for MaCFP-2, I realised that they contained a README. Did the files get lost somehow or did I not submit it last time? 

Anyway, I've now adjusted the file structure in the `Material_Properties` directory to reflect the structure from the `Calibration_Data` directory, see new pull request.

**Pull request closed without merging**
