### PR TITLE
mckinnonm: added FSRI PMMA data

### PR DESCRIPTION
**Pull request by mckinnonm**

### CODE REVIEW

**Comment by leventon** [comment]
Again, please make sure that your file format (Column order) matches that of other data sets: 
TGA [time Temperature Mass] 
DSC [time Temperature heat flow]

Also, one of your files has 4000 rows of comas/zero data. please remove that too before resubmitting.

**Comment by rmcdermo** [comment]
@leventon Let's discuss this.  Column order should not matter.  Python easily grabs columns based on header names.  If our scripts are relying on columns being in a certain order, that is a problem.

**Comment by leventon** [comment]
@mckinnonm we will update our scripts to provide flexibility in how data can be read in, that's on the to do list, but, for now, please format your TGA/DSC data to match the other measurements on the repo. 
TGA [time Temperature Mass]
DSC [time Temperature heat flow]

If you can run Import_Data.m and then either TGA_Analysis.m or DSC_Analysis.m, and then your data is plotted along with all the other sets - that's confirmation that things have been submitted correctly.

**Comment by rmcdermo** [comment]
Closing this PR.  Please fix files and submit a new one if this is still applicable.

**Pull request closed without merging**
