### PR TITLE
Section 3, update subsubheaders

### PR DESCRIPTION
**Pull request by leventon**

### CODE REVIEW

**Comment by rmcdermo** [comment]
@leventon Sorry, but I had not merged Kevin's changes before you submitted these.

You need to reset your changes and merge the central repo and then send a new PR.  Thanks

**Comment by leventon** [comment]
Okay, will do. Minor fixes at least.

**Comment by mcgratta** [comment]
I already changed \paragraph to \subsubsection when I realized that it was more appropriate. I think you might run into a conflict when you merge. Always do a merge before working on the document. I'm surprised GitHub let you do a pull request.

**Comment by rmcdermo** [comment]
Kevin,
When Isaac did his PR, I had not yet merged your stuff.  So, I suspect all was fine at that point.  Had I merged his stuff first, your PR would then have been broken.  But I went chronologically.

**Comment by mcgratta** [comment]
OK, is everything settled then?

**Comment by rmcdermo** [comment]
No.  Isaac has not submitted a new PR with conflicts resolved.

**Comment by leventon** [comment]
I've been on campus for two hours dealing with a messed up TGA delivery.
Will focus back on this when home.

**Comment by mcgratta** [comment]
No worries. I made the same changes as you in my commit. 
Randy -- what is the ritual for eliminating the commit that Isaac made to his forked repo?

**Comment by rmcdermo** [comment]
Two options:
1. Reset to the commit before.  Then do a forced push.
2. Merge the central repo and fix conflicts.  Then commit and send PR.

**Comment by mcgratta** [comment]
Option 2 might be best. There are only a handful of changes that Isaac made, and I had already made them. So maybe the number of conflicts will be small.

**Pull request closed without merging**
